sudo: required
language: generic

services:
   - docker

before_install:
   - docker build -t duttasayan666/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true duttasayan666/docker-react npm run test -- --coverage
